#!/bin/bash

LOG_ASSEMBLY="$1"
CODICE_CAMPIONE="$2"
FAILURES_FILE="$3"

# Log files generated by Spades
#log_file="./spades.log"

# File where failed samples are noted
#output_file="./campioni_falliti.txt"

# Looking for failed samples via the log files, saving results in variable
failed_samples=$(grep "finished abnormally" $LOG_ASSEMBLY)          #$log_file)

# Checks if variable contains failed samples
if [ -n "$failed_samples" ]; then
    # If any samples are present, they are noted in the output file
    echo "Campione con assemblaggio fallito: ${CODICE_CAMPIONE} salvato:" >> ${FAILURES_FILE}      #$output_file
    echo "$failed_samples" >> ${FAILURES_FILE} #$output_file
    echo "\n" >> ${FAILURES_FILE} #$output_file
    echo "\n" >> ${FAILURES_FILE} #$output_file
    echo "\n" >> ${FAILURES_FILE} #$output_file
else
    # If no failed samples are present: 
    echo "\n" >> ${FAILURES_FILE}
    echo "\n" >> ${FAILURES_FILE}
    echo "Nessun assemblaggio fallito trovato: ${CODICE_CAMPIONE} prosegue normalmente l'analisi !" >> ${FAILURES_FILE}
    echo "\n" >> ${FAILURES_FILE} #$output_file
    echo "\n" >> ${FAILURES_FILE} #$output_file
    echo "\n" >> ${FAILURES_FILE} #$output_file
fi

